spring.application.name=GlamourStudio
spring.datasource.url=jdbc:postgresql://localhost:5432/glamourstudio-db
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.d ialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.expiracao = 5
spring.secret = "sksdmsdefoi4409i9tkdfogkpog3443itd"
spring.emissor = "vanessa"